import "./styles/globals.css";
import { BlitzProvider } from "./blitz-client";
import { invoke } from "@/src/app/blitz-server";
import getCurrentUser from "@/src/app/users/queries/getCurrentUser";
import { Metadata } from "next";
import { LogoutButton } from "@/src/app/(auth)/components/LogoutButton";
import Link from "next/link";

export const metadata: Metadata = {
  title: "New Blitz App",
  description: "Generated by blitz new",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const currentUser = await invoke(getCurrentUser, null);

  return (
    <html lang="en">
    <body>
    <BlitzProvider>
      <div className="root">
        <header className="appBar">
          <div className="toolbar">
            <h1 className="title">Chess App</h1>
            {currentUser ? (
              <div className="user-info">
                <span className="welcomeText">Welcome back, {currentUser.name}!</span>
                <LogoutButton />
              </div>
            ) : (
              <div className="auth-buttons">
                <Link href="/login" className="loginButton">Login</Link>
                <Link href="/signup" className="signupButton">Sign Up</Link>
              </div>
            )}
          </div>
        </header>

        <main className="main">{children}</main>

        <footer className="footer">
          <p>Powered by Uchiha Chess Clan</p>
        </footer>
      </div>
    </BlitzProvider>
    </body>
    </html>
  );
}
